package]
name = "storm"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
rand = "0.8"
tokio = { version = "1.0", features = ["full"] }
url = "2.0"
regex = "1.0"
